server:
  port: 7708

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservicedb
    username: root
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
